version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: products_db
  app:
    build: .
    ports:
      - "8802:80"
    depends_on:
      - db
    links:
      - db