server:
  address: 0.0.0.0
  port: 80

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/products_db
    username: postgres
    password: 1234

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update